### ISSUE TITLE
Enable `go vet` in CI

### ISSUE THREAD

**Issue by samuelkarp** [awslabs/amazon-ecr-containerd-resolver#3]
According to @petderek, go vet is "like having a pedantic coworker [and] it's great".

```
$ go vet ./ecr/...
# github.com/samuelkarp/amazon-ecr-containerd-resolver/ecr
ecr/layer_writer.go:53:2: the cancel function is not used on all paths (possible context leak)
ecr/layer_writer.go:73:3: this return statement may be reached without using the cancel var defined on line 53
ecr/fetcher.go:71:2: unreachable code
ecr/pusher.go:61:2: unreachable code
```

Nothing major right now, but it seems worthwhile to fix.

**Comment by jahkeup** [comment]
This can close now that #14 is merged. [`go vet` is run by `golangci-lint` by default](https://golangci-lint.run/usage/linters/#enabled-by-default-linters).

---

Here's an [example run](https://github.com/awslabs/amazon-ecr-containerd-resolver/runs/782343033#step:3:65), it's rather quiet because the existing lints were fixed as part of the PR enabling the check.

**Comment by samuelkarp** [comment]
Thanks @jahkeup!
